import { PluginOption } from 'vite';
import { minify } from 'html-minifier';

export default (): PluginOption => {
  return {
    name: 'build',
    apply: 'build',
    enforce: 'pre',
    transformIndexHtml(code) {
      return minify(code, {
        minifyJS: true,
        includeAutoGeneratedTags: true,
        removeAttributeQuotes: true,
        removeComments: true,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true,
        sortClassName: true,
        useShortDoctype: true,
        collapseWhitespace: true,
      });
    },
  };
};
