name: Deploy to github pages
on:
  push:
    branches:
      # - main
      - develop
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - uses: xRealNeon/VuePagesAction@bb1a496e439e523025f6f37a2bd37ce8a8835c04
        with:
          username: 'Lipoic'
          reponame: 'Lipoic-Frontend'
          token: ${{ secrets.LIPOIC_GITHUB_TOKEN }}
          gitmsg: Deploy to github pages
          gitname: Github action bot
          cname: 'lipoic.org'
          useyarn: true
