name: Pull request review
on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v11
        with:
          token: ${{ github.token }}
          config_path: '.eslintrc.js'
          file_extensions: |
            **/*.js            
            **/*.ts
            **/*.vue
            **/*.scss
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Create deployment
        id: create_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments
          repository: ${{ github.repository }}
          required_contexts: '[]'
          environment: pull_request_review
          ref: ${{ github.head_ref }}
          auto_merge: false
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Set deployment status
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ fromJson(steps.create_deployment.outputs.data).id }}
          environment: pull_request_review
          environment_url: https://deploy-preview-${{ github.event.pull_request.number }}--lipoic-frontend.netlify.app
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          description: 'Preview the page: https://deploy-preview-${{ github.event.pull_request.number }}--lipoic-frontend.netlify.app'
          mediaType: '{"previews": ["ant-man"]}'
          state: success
        env:
          GITHUB_TOKEN: ${{ github.token }}
