name: Pull request review
on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v11
        with:
          token: ${{ github.token }}
          config_path: '.eslintrc.js'
          file_extensions: |
            **/*.js            
            **/*.ts
            **/*.vue
            **/*.scss
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create deployment
        id: create_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments
          repository: ${{ github.repository }}
          required_contexts: '[]'
          environment: pull_request_review
          ref: ${{ github.head_ref }}
          auto_merge: false
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set deployment status to pending
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ fromJson(steps.create_deployment.outputs.data).id }}
          environment: pull_request_review
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          mediaType: '{"previews": ["ant-man"]}'
          state: in_progress
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy Preview to Netlify
        id: deploy_preview
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './dist'
          github-token: ${{ github.token }}
          deploy-message: 'Deploy Preview from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: deploy-preview-${{ github.event.number }}
          github-deployment-environment: pull_request_review
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

      - name: Set deployment status to success
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ fromJson(steps.create_deployment.outputs.data).id }}
          environment: pull_request_review
          environment_url: ${{ steps.deploy_preview.outputs.deploy-url }}
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          description: 'Preview the page: ${{ steps.deploy_preview.outputs.deploy-url }}'
          mediaType: '{"previews": ["ant-man"]}'
          state: success
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set deployment status to failure
        uses: octokit/request-action@v2.x
        if: failure()
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ fromJson(steps.create_deployment.outputs.data).id }}
          environment: pull_request_review
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          mediaType: '{"previews": ["ant-man"]}'
          state: failure
        env:
          GITHUB_TOKEN: ${{ github.token }}
